-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."borrow_status" AS ENUM('BORROWED', 'RETURNED');--> statement-breakpoint
CREATE TYPE "public"."role" AS ENUM('USER', 'ADMIN');--> statement-breakpoint
CREATE TYPE "public"."status" AS ENUM('PENDING', 'APPROVED', 'REJECTED');--> statement-breakpoint
CREATE TABLE "books" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "books_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" text DEFAULT '' NOT NULL,
	"image" text,
	"author" text DEFAULT '' NOT NULL,
	"created_at" timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"genre" text[] DEFAULT '{""}' NOT NULL,
	"summary" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "books" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"full_name" varchar(255) NOT NULL,
	"university_id" integer,
	"role" "role" DEFAULT 'USER' NOT NULL,
	"status" "status" DEFAULT 'PENDING' NOT NULL,
	"last_activity_date" date DEFAULT now(),
	"created_at" timestamp with time zone DEFAULT now(),
	"Borrowed_books" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_auth_fk" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "Authenticated users can read books" ON "books" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "books_delete" ON "books" AS PERMISSIVE FOR DELETE TO "authenticated";--> statement-breakpoint
CREATE POLICY "books_update" ON "books" AS PERMISSIVE FOR UPDATE TO "authenticated";--> statement-breakpoint
CREATE POLICY "users_delete_based_on_role" ON "users" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'USER'::text) AND (id = auth.uid())) OR (((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'ADMIN'::text)));--> statement-breakpoint
CREATE POLICY "users_read_based_on_role" ON "users" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "users_update_based_on_role" ON "users" AS PERMISSIVE FOR UPDATE TO "authenticated";
*/